config/routes.rb
Rails.application.routes.draw do

  resources :colleges do
    resources :participants
  end

  devise_for :admins
  
  root 'home#index'

  get '/about/anugoonj'       => 'home#about_anugoonj'
  get '/about/college'        => 'home#about_college'
  get '/about/coordinators'   => 'home#coordinators'
  get '/events/intra-college' => 'home#intra_college_events'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable #, :registerable,
         # :recoverable, :rememberable, :trackable, :validatable
end

app/models/college.rb
class College < ActiveRecord::Base

  has_many :participants, dependent: :destroy
  accepts_nested_attributes_for :participants
  
  validates :name,        presence: true

  validates :group_name,  presence: true,
                          uniqueness: { case_sensitive: false }

  validates :contact_no,  presence: true,
                          numericality: true,
                          length: { is: 10 },
                          uniqueness: true
end

app/models/participant.rb
class Participant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:new, :create, :show]

  # GET /colleges
  # GET /colleges.json
  def index
    @colleges = College.all.order('created_at DESC')
  end

  # GET /colleges/1
  # GET /colleges/1.json
  def show
  end

  # GET /colleges/new
  def new
    @college = College.new
    if ["poetry_meet", "fusion_of_bands", "short_movie_making", "technical_projects_exhibition"].include? params[:event]
      @college.event = params[:event]
    else
      redirect_to root_path, alert: 'Please select an event.'
    end
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges
  # POST /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to @college, notice: 'College was successfully registered.' }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1
  # PATCH/PUT /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to @college, notice: 'College details were successfully updated.' }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1
  # DELETE /colleges/1.json
  def destroy
    @college.destroy
    respond_to do |format|
      format.html { redirect_to colleges_url, notice: 'College was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def college_params
      params.require(:college).permit(:name, :group_name, :contact_no, :confirmed, :event)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about_college
  end

  def about_anugoonj
  end

  def coordinators
  end

  def intra_college_events
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :email, :contact_no, :college_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/colleges/_form.html.haml
- if @college.errors.any?
  .alert.alert-danger
    %h3
      = pluralize(@college.errors.count, "error")
      prohibited this college from being registered:
    %ol
      - @college.errors.full_messages.each do |msg|
        %li= msg
= form_for @college, html: { class: "form form-horizontal college" } do |f|
  .form-group.hidden
    = f.label :event, class: 'control-label col-sm-3'
    .col-sm-9
      = f.text_field :event, class: 'form-control', required: true
    = error_span(@college[:event])
  .form-group
    = f.label :name, class: 'control-label col-sm-3'
    .col-sm-9
      = f.text_field :name, class: 'form-control', required: true, placeholder: "Write your full college name"
    = error_span(@college[:name])
  .form-group
    = f.label :group_name, class: 'control-label col-sm-3'
    .col-sm-9
      = f.text_field :group_name, class: 'form-control', required: true, placeholder: "Give your group/team a name"
    = error_span(@college[:group_name])
  .form-group
    = f.label :contact_no, class: 'control-label col-sm-3'
    .col-sm-9
      .input-group
        .input-group-addon +91
        = f.text_field :contact_no, class: 'form-control', required: true, placeholder: "The college's contact number."
    = error_span(@college[:contact_no])

  .text-right
    = f.submit "Register college", class: 'btn btn-primary'
    = link_to "Abort", :back, :class => 'btn btn-warning'

app/views/colleges/_fusion_of_bands.html.haml
.jumbotron
  %h1
    Junoon
    %small Fusion of bands
    
  %p Music is the universal language that allows all people to communicate with each other. Hence we have a contest where bands compete for the title of the “Best Troop”.
  
  %h2 Rules & Regulations
  
  %ul
    %li
      %strong A Maximum of 8 members are allowed in a team.
    %li
      %strong 
        Entry fees of Rs. 1500/- per team.
        %br/
        If the team has more than 5 members, then the entry fees would be Rs. 300/- per member.
    %li
      %strong Time limit:
      30 minutes (including sound check).
    %li Participants would have to bring their own instruments.
    %li Negative points for exceeding the time limit.
    %li Judgement will be made on the basis of instrument handling and innovation.
    %li Decision of the Judges will be final.
  
  %blockquote
    FOR FURTHER DETAILS CONTACT THE UNDERSIGNED
    .text-left
      %strong Sanjay Pant
      +918267831287
    .text-left
      %strong Mehtab Ali
      +918395056973

app/views/colleges/_poetry_meet.html.haml
.jumbotron
  %h1
    Kavyanjali
    %small Poetry Meet
    
  %blockquote
    %p
      Raise your words, not the voice.
      %br/
      It is the rain which grows the flower, not the thunder.
  
  %h2 Rules and Regulations

  %ul
    %li 
      %strong Only one Entry per person.
    %li
      %strong Entry fees will be 100/- per participant.
    %li Poems can be both in Hindi/English.
    %li All work must be original and unaided.
    
  %blockquote
    FOR FURTHER DETAILS CONTACT THE UNDERSIGNED
    .text-left
      %strong Vivek Pal
      +919690460701
    .text-left
      %strong Aadil Firoze
      +918266806486

app/views/colleges/_short_movie_making.html.haml
.jumbotron
  %h1
    Varnam 
    %small Short Movie Making Competition
    
  %p Filmmaking, like any other art, is a very profound means of human communication. Beyond the professional pleasure of succeeding or the pain of failing, you do want your film to be seen to communicate itself to other people.
  
  %h2 Rules and Regulations
  
  %ul
    %li
      %strong Maximum 6 members in a team (including cast & crew).
    %li
      %strong Entry fees will be 500/- per team.
    %li Director or Co-Director will represent the team.
    %li
      Film should be in
      %strong .wmv
      format a maximum of
      %strong 720p
      and not less than
      %strong 240p.
    %li Abusive, adult or religious content are strictly prohibited.
    %li Film should not be older than 3 months (Date should be mentioned visually at the start of the film).
    %li Length of the film should not exceed the duration of 15 minutes including the titles and texts.
    %li Film should either be in Hindi, English or a mime.
    %li Film should not be a documentary.
    
  %blockquote
    FOR FURTHER DETAILS CONTACT THE UNDERSIGNED
    .text-left
      %strong Shishir Raj Singh
      +918979885445
    .text-left
      %strong Madhukant Mukherjee
      +919045371872

app/views/colleges/_technical_projects_exhibition.html.haml
.jumbotron
  %h1
    Inventar
    %small Technical Projects Exhibition
    
  %p Exhibition means to show cast your talent. Here talent should be related to the technical model.
  
  %h2 Rules and Regulations
  
  %ul
    %li
      %strong Maximum of 3 members in a team.
    %li
      %strong Entry fees will be 500/- per team.
    %li The team participating here has to bring the working model of any project and have to describe their project.
    %li Participants need to carry their identity cards.
    %li The best working model will be chosen.
    %li Winner will be declared as per the new innovation.
    
  %blockquote
    FOR FURTHER DETAILS CONTACT THE UNDERSIGNED
    .text-left
      %strong Prashant Dwivedi
      +919452037685
    .text-left
      %strong Aadil Firoze
      +918266806486

app/views/colleges/edit.html.haml
.col-md-2
.well.col-md-8
  %legend
    %h2
      Edit college registration
      %small
        for
        = @college.event.titleize
  = render "form"
.col-md-2

app/views/colleges/index.html.haml
.jumbotron
  %h1 Manage colleges
  %table.table.table-hover
    %thead
      %tr
        %th ID
        %th Name of college
        %th Group name
        %th Contact Number
        %th Confirmed
        %th Event
        %th Created
        %th Actions
    %tbody
      - @colleges.each do |college|
        %tr
          %td= link_to college.id, college_path(college)
          %td= college.name
          %td= college.group_name
          %td= college.contact_no
          %td
            - if college.confirmed?
              Yes
            - else
              No
          %td= college.event.titleize
          %td= college.created_at.to_s
          %td
            = link_to "Edit", edit_college_path(college), class: 'btn btn-warning btn-sm'
            = link_to "Delete", college_path(college), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

  = link_to "New", new_college_path, :class => 'btn btn-primary'

app/views/colleges/new.html.haml
= render @college.event
.col-md-2
.well.col-md-8
  %legend
    %h1
      Register your college
      %small
        for
        = @college.event.titleize
  = render "form"
.col-md-2

app/views/colleges/show.html.haml
.jumbotron
  %legend
    %h2
      College registration details
      %small
        for
        = @college.event.titleize

  %p
    %strong College name
    %br
    = @college.name
  %p
    %strong Group name
    %br
    = @college.group_name
  %p
    %strong Contact number
    %br
    = @college.contact_no
  - if admin_signed_in?
    %p
      %strong Confirmed
      %br
      - if @college.confirmed?
        Yes
      - else
        No

  - if admin_signed_in?
    = link_to "Back", colleges_path, :class => 'btn btn-info'
    = link_to "Edit", edit_college_path(@college), :class => 'btn btn-warning'
    = link_to "Delete entry", college_path(@college), :method => "delete", :data => { confirm: 'Are you sure?' }, :class => 'btn btn-danger'
  - else
    %p
      %strong Note: 
      Each participant would receive an email from us, once the registration entry is confirmed.

app/views/home/about_anugoonj.html.haml
.jumbotron
  %h1 
    Anugoonj
    %small 2015
  %p And here's something about our annual cultural festival!

app/views/home/about_college.html.haml
.well
  %legend
    %h1
      Welcome
      %small to Roorkee Institute of Technology
  

app/views/home/coordinators.html.haml
%center
  .jumbotron
    %h1 Coordinators

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/sanjay_pant.jpg')}" style="width:60%;")
      .caption
        %h3 
          Sanjay Pant

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/rahul_jadli.jpg')}" style="width:60%;")
      .caption
        %h3 
          Rahul Jadli

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/aadil_firoze.jpg')}" style="width:60%;")
      .caption
        %h3 
          Aadil Firoze

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/sameer_ansaari.jpg')}" style="width:60%;")
      .caption
        %h3 
          Sameer Ansaari

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/prashant_dwivedi.jpg')}" style="width:60%;")
      .caption
        %h3 
          Prashant Dwivedi

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/shishir_raj_singh.jpg')}" style="width:60%;")
      .caption
        %h3 
          Shishir Raj Singh

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/anwar_hussain.jpg')}" style="width:60%;")
      .caption
        %h3 
          Anwar Hussain

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/chandra_prakash_dubey.jpg')}" style="width:60%;")
      .caption
        %h3 
          Chandra Prakash Dubey

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/vivek_pal.jpg')}" style="width:60%;")
      .caption
        %h3 
          Vivek Pal

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/vimal_vaibhav.jpg')}" style="width:60%;")
      .caption
        %h3 
          Vimal Vaibhav

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/ashwani_prajapati.jpg')}" style="width:60%;")
      .caption
        %h3 
          Ashwani Prajapati

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/akshay_dhiman.jpg')}" style="width:60%;")
      .caption
        %h3 
          Akshay Dhiman

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/vinod_rana.jpg')}" style="width:60%;")
      .caption
        %h3 
          Vinod Rana

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/rohan_dhek.jpg')}" style="width:60%;")
      .caption
        %h3 
          Rohan Dhek

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/varun_batra.jpg')}" style="width:60%;")
      .caption
        %h3 
          Varun Batra

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/pranjal_nadhani.jpg')}" style="width:60%;")
      .caption
        %h3 
          Pranjal Nadhani

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/deshbandhu_kumar.jpg')}" style="width:60%;")
      .caption
        %h3 
          Deshbandhu Kumar

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/mehtab_ali.jpg')}" style="width:60%;")
      .caption
        %h3 
          Mehtab Ali

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/ritu_gupta.jpg')}" style="width:60%;")
      .caption
        %h3 
          Ritu Gupta

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/pallavi_rajput.jpg')}" style="width:60%;")
      .caption
        %h3 
          Pallavi Rajput

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/akansha_tripathi.jpg')}" style="width:60%;")
      .caption
        %h3 
          Akansha Tripathi

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/soni_aggrawal.jpg')}" style="width:60%;")
      .caption
        %h3 
          Soni Aggrawal

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/nainsi_gupta.jpg')}" style="width:60%;")
      .caption
        %h3 
          Nainsi Gupta

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/sadiya_naaz.jpg')}" style="width:60%;")
      .caption
        %h3 
          Sadiya Naaz

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/mamta_bhandari.jpg')}" style="width:60%;")
      .caption
        %h3 
          Mamta Bhandari

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/sonali_gupta.jpg')}" style="width:60%;")
      .caption
        %h3 
          Sonali Gupta

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/anjali_roy.jpg')}" style="width:60%;")
      .caption
        %h3 
          Anjali Roy

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/yukta_mishra.jpg')}" style="width:60%;")
      .caption
        %h3 
          Yukta Mishra

  .col-sm-3
    .thumbnail
      %br/
      %img.img-circle(src="#{asset_path('coordinators/jyoti_yadav.jpg')}" style="width:60%;")
      .caption
        %h3 
          Jyoti Yadav

app/views/home/index.html.haml
#anugoonj-carousel.carousel.slide
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#anugoonj-carousel"}
    %li{"data-slide-to" => "1", "data-target" => "#anugoonj-carousel"}
    %li{"data-slide-to" => "2", "data-target" => "#anugoonj-carousel"}
    %li{"data-slide-to" => "3", "data-target" => "#anugoonj-carousel"}
    %li{"data-slide-to" => "4", "data-target" => "#anugoonj-carousel"}
  / Wrapper for slides
  .carousel-inner
    .item.active
      %img{:alt => "", :src => "#{asset_path('banner/1.jpg')}"}
        .carousel-caption
          %h1#banner1 Anugoonj 2015
    .item
      %img{:alt => "", :src => "#{asset_path('banner/2.jpg')}"}
        .carousel-caption
          %h1#banner1 Anugoonj 2015
    .item
      %img{:alt => "", :src => "#{asset_path('banner/3.jpg')}"}
        .carousel-caption
          %h1#banner1 Anugoonj 2015
    .item
      %img{:alt => "", :src => "#{asset_path('banner/4.jpg')}"}
        .carousel-caption
          %h1#banner1 Anugoonj 2015
    .item
      %img{:alt => "", :src => "#{asset_path('banner/5.jpg')}"}
        .carousel-caption
          %h1#banner1 Anugoonj 2015
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#anugoonj-carousel"}
    %span.icon-prev
  %a.right.carousel-control{"data-slide" => "next", :href => "#anugoonj-carousel"}
    %span.icon-next

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Anugoonj"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container-fluid
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Anugoonj", root_path, class: "navbar-brand"
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.navbar-right
            - if admin_signed_in?
              %li.navbar-text
                Signed in as
                = current_admin.email
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
                  Manage
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Colleges", colleges_path
                  %li= link_to "Queries", ""
              %li= link_to "Logout", destroy_admin_session_path, method: :delete
            - else
              %li= link_to "Intra-college events", events_intra_college_path
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
                  Inter-college events
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Poetry Meet", new_college_path(event: :poetry_meet)
                  %li= link_to "Fusion of bands", new_college_path(event: :fusion_of_bands)
                  %li= link_to "Short Movie Making", new_college_path(event: :short_movie_making)
                  %li= link_to "Technical Projects Exhibition", new_college_path(event: :technical_projects_exhibition)
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: ""}
                  About
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to "Anugoonj", about_anugoonj_path
                  %li= link_to "College", about_college_path
                  %li= link_to "Coordinators", about_coordinators_path

    %nav#loading.navbar.navbar-default.navbar-fixed-bottom{role: "navigation", style: "display: none;"}
      %center
        %p.navbar-text The page is loading. This might take a few seconds depending on your internet speed...

    .container-fluid
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

app/views/participants/_form.html.haml
= form_for @participant do |f|
  - if @participant.errors.any?
    #error_explanation
      %h2= "#{pluralize(@participant.errors.count, "error")} prohibited this participant from being saved:"
      %ul
        - @participant.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :contact_no
    = f.text_field :contact_no
  .field
    = f.label :college_id
    = f.number_field :college_id
  .actions
    = f.submit 'Save'

app/views/participants/edit.html.haml
%h1 Editing participant

= render 'form'

= link_to 'Show', @participant
\|
= link_to 'Back', participants_path

app/views/participants/index.html.haml
%h1 Listing participants

%table
  %thead
    %tr
      %th Name
      %th Email
      %th Contact no
      %th College
      %th
      %th
      %th

  %tbody
    - @participants.each do |participant|
      %tr
        %td= participant.name
        %td= participant.email
        %td= participant.contact_no
        %td= participant.college_id
        %td= link_to 'Show', participant
        %td= link_to 'Edit', edit_participant_path(participant)
        %td= link_to 'Destroy', participant, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Participant', new_participant_path

app/views/participants/new.html.haml
%h1 New participant

= render 'form'

= link_to 'Back', participants_path

app/views/participants/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @participant.name
%p
  %b Email:
  = @participant.email
%p
  %b Contact no:
  = @participant.contact_no
%p
  %b College:
  = @participant.college_id

= link_to 'Edit', edit_participant_path(@participant)
\|
= link_to 'Back', participants_path